# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-20 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=16, unique=True, verbose_name='账号')),
                ('username', models.CharField(max_length=11, verbose_name='昵称')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('head_img', models.ImageField(default='', upload_to='static/image', verbose_name='头像')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
