# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-21 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='活跃状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(default='student', max_length=11, verbose_name='角色'),
        ),
    ]
